mv ./world-population/target/world-population.car.jar        ./world-population/target/world-population.car
mv ./vanity-urls/target/vanity-urls.car.jar                  ./vanity-urls/target/vanity-urls.car
mv ./bootstrap-layouts/target/bootstrap-layouts.car.jar      ./bootstrap-layouts/target/bootstrap-layouts.car
mv ./user-forms/target/user-forms.car.jar                    ./user-forms/target/user-forms.car 
mv ./sitemap/target/sitemap.car.jar                          ./sitemap/target/sitemap.car 
mv ./rss-feed/target/rss-feed.car.jar                        ./rss-feed/target/rss-feed.car 
mv ./rich-text/target/rich-text.car.jar                      ./rich-text/target/rich-text.car 
mv ./custom-error-pages/target/custom-error-pages.car.jar    ./custom-error-pages/target/custom-error-pages.car 
mv ./jquery-slider/target/jquery-slider.car.jar              ./jquery-slider/target/jquery-slider.car 
mv ./blogs/target/blog.car.jar                               ./blogs/target/blog.car 
mv ./search-page/target/search-page.car.jar                  ./search-page/target/search-page.car 
mv ./weather-site-azilen/target/weather-site-azilen.car.jar  ./weather-site-azilen/target/weather-site-azilen.car 
mv ./alfresco-activiti/target/alfresco-activiti.car.jar      ./alfresco-activiti/target/alfresco-activiti.car 
mv ./dynamic-navigation/target/dynamic-navigation.car.jar    ./dynamic-navigation/target/dynamic-navigation.car 
mv ./social-sharing/target/social-sharing.car.jar            ./social-sharing/target/social-sharing.car 
mv ./google-analytics/target/google-analytics.car.jar        ./google-analytics/target/google-analytics.car 
mv ./crafter-social/target/crafter-social.car.jar            ./crafter-social/target/crafter-social.car 
mv ./profile/target/profile.car.jar                          ./profile/target/profile.car 
mv ./twitterfeed/target/twitterfeed.car.jar                  ./twitterfeed/target/twitterfeed.car 
mv ./youtube-video/target/youtube-video.car.jar              ./youtube-video/target/youtube-video.car 
mv ./qr-code/target/qr-code.car.jar                          ./qr-code/target/qr-code.car 
